title: Fernando's Notebook
description: > # this means to ignore newlines until "baseurl:"
  Fernando's public notebook
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://https://fernandolrubio.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Fernando L. Rubio # add your name
author-img: author.jpg # add your photo
about-author: Public notebook. # add description
social-github: # add your Github handle
social-linkedin: # add your Linkedin handle

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
